/*
 * check-capture-sidecar -- what a capture says about its own bytes.
 *
 * A raw .bin is bytes, and reading one correctly needs to know the container.
 * That fact lived in the sidecar's prose where nothing could read it; it is a
 * field now. This suite covers the reading, including the two refusals that
 * are the point of having it.
 */

#include "check.h"

#include "capture_sidecar.h"

/* A sidecar as scripts/rescale_capture.c writes one. */
static const char *const S16_SIDECAR =
    "{\n"
    "  \"provenance\": \"generated by scripts/rescale_capture\",\n"
    "  \"format\": \"signed 16-bit little-endian interleaved I/Q, 0 = zero\",\n"
    "  \"full_scale\": 2040.0,\n"
    "  \"bytes_per_pair\": 4,\n"
    "  \"center_frequency_hz\": 948400000,\n"
    "  \"sample_rate_hz\": 2000000,\n"
    "  \"gain_db\": null,\n"
    "  \"bytes\": 16252928\n"
    "}\n";

/* A sidecar as testfiles/ carries one: prose, and no full scale at all. */
static const char *const U8_SIDECAR =
    "{\n"
    "  \"provenance\": \"reconstructed 2026-08-30\",\n"
    "  \"format\": \"unsigned 8-bit interleaved I/Q, 127.5 = zero\",\n"
    "  \"center_frequency_hz\": 948400000,\n"
    "  \"sample_rate_hz\": 2000000,\n"
    "  \"gain_db\": null,\n"
    "  \"ppm\": null,\n"
    "  \"bytes\": 8126464\n"
    "}\n";

static void test_a_generated_sidecar_reads_whole(void) {
    struct capture_sidecar c;
    check_int("it parses", capture_sidecar_parse(S16_SIDECAR, &c), 0);
    check_int("four bytes a pair means S16", (int)c.format,
              SAMPLE_FORMAT_S16);
    check_close("full scale is the corpus's 2040", c.full_scale, 2040.0, 1e-6);
    check_true("and it was stated, not assumed", c.full_scale_stated != 0);
    check_true("as was the format", c.format_stated != 0);
}

/*
 * Every capture that existed before this said nothing readable about its
 * container, and must keep reading as the house convention -- otherwise the
 * whole of testfiles/ stops decoding.
 */
static void test_an_old_sidecar_is_the_house_convention(void) {
    struct capture_sidecar c;
    check_int("it parses", capture_sidecar_parse(U8_SIDECAR, &c), 0);
    check_int("8-bit", (int)c.format, SAMPLE_FORMAT_U8);
    check_close("at 127.5", c.full_scale, 127.5, 1e-6);
    check_true("assumed, not stated", c.full_scale_stated == 0);
    check_true("the format was not stated either", c.format_stated == 0);

    /* No sidecar at all is the same answer. Most captures predate them. */
    check_int("no text parses too", capture_sidecar_parse(NULL, &c), 0);
    check_int("and is 8-bit", (int)c.format, SAMPLE_FORMAT_U8);
    check_close("at 127.5", c.full_scale, 127.5, 1e-6);

    /* A null in a field is absent, not zero -- several reconstructed sidecars
       carry them and a zero full scale would be a division by it. */
    int found = 1;
    check_close("a null reads as absent",
                capture_sidecar_number(U8_SIDECAR, "gain_db", -1.0, &found),
                -1.0, 1e-9);
    check_int("and says so", found, 0);
}

/*
 * The refusal, which is the whole reason full scale is a field.
 *
 * Two 16-bit sources rail at 2040.0 and 2047.5. `device_default_full_scale`
 * returns 0 for S16 rather than guessing, so a capture that names a 16-bit
 * container without naming its rail cannot be read in dBFS at all -- and
 * saying so beats picking one and being quietly wrong by 0.03 dB everywhere.
 */
static void test_a_16_bit_capture_must_state_its_full_scale(void) {
    static const char *const silent =
        "{\n"
        "  \"format\": \"signed 16-bit little-endian interleaved I/Q\",\n"
        "  \"bytes_per_pair\": 4,\n"
        "  \"sample_rate_hz\": 2000000\n"
        "}\n";
    struct capture_sidecar c;
    check_int("refused", capture_sidecar_parse(silent, &c), -1);

    /* The same sidecar with the rail named is fine, whichever rail it is. */
    static const char *const part =
        "{\n"
        "  \"bytes_per_pair\": 4,\n"
        "  \"full_scale\": 2047.5\n"
        "}\n";
    check_int("a real 12-bit part parses", capture_sidecar_parse(part, &c), 0);
    check_close("at its own rail", c.full_scale, 2047.5, 1e-6);
    check_true("which is not the corpus's", c.full_scale != 2040.0f);
}

/* The prose fallback, for a 16-bit sidecar written before bytes_per_pair. */
static void test_the_format_string_is_the_fallback(void) {
    static const char *const prose =
        "{\n"
        "  \"format\": \"signed 16-bit little-endian interleaved I/Q\",\n"
        "  \"full_scale\": 2040.0\n"
        "}\n";
    struct capture_sidecar c;
    check_int("it parses", capture_sidecar_parse(prose, &c), 0);
    check_int("prose names the container", (int)c.format, SAMPLE_FORMAT_S16);

    /* But "16-bit" appearing far from the format key is not the format. A
       note mentioning a 16-bit anything must not change how bytes are read. */
    static const char *const note =
        "{\n"
        "  \"format\": \"unsigned 8-bit interleaved I/Q\",\n"
        "  \"notes\": [\"the Fire code is a 16-bit shortened cyclic code\"]\n"
        "}\n";
    check_int("it parses", capture_sidecar_parse(note, &c), 0);
    check_int("and stays 8-bit", (int)c.format, SAMPLE_FORMAT_U8);
}

static void test_the_sidecar_path_rule(void) {
    char path[64];
    capture_sidecar_path("testfiles/gsm_arfcn_69.bin", path, sizeof(path));
    check_str("bin becomes json", path, "testfiles/gsm_arfcn_69.json");
    capture_sidecar_path("captures/raw", path, sizeof(path));
    check_str("no extension appends", path, "captures/raw.json");
    capture_sidecar_path(NULL, path, sizeof(path));
    check_str("a null path is empty", path, ".json");
}

/* The real corpora, which is what the program will actually meet. */
static void test_the_corpora_on_disk(void) {
    struct capture_sidecar c;

    if (capture_sidecar_read("testfiles/gsm_arfcn_69.bin", &c) == 0) {
        check_int("testfiles/ is 8-bit", (int)c.format, SAMPLE_FORMAT_U8);
        check_close("at 127.5", c.full_scale, 127.5, 1e-6);
    } else {
        check_true("testfiles/gsm_arfcn_69.json reads", 0);
    }

    if (capture_sidecar_read("build/testfiles16/gsm_arfcn_69.bin", &c) == 0) {
        check_int("the generated corpus is 16-bit", (int)c.format,
                  SAMPLE_FORMAT_S16);
        check_close("at 2040", c.full_scale, 2040.0, 1e-6);
        check_true("and says so itself", c.full_scale_stated != 0);
    } else {
        check_true("build/testfiles16/gsm_arfcn_69.json reads", 0);
    }

    /* A capture with no sidecar beside it is not an error. */
    check_int("a missing sidecar is the house convention",
              capture_sidecar_read("no/such/capture.bin", &c), 0);
    check_int("8-bit", (int)c.format, SAMPLE_FORMAT_U8);
}

int main(void) {
    test_a_generated_sidecar_reads_whole();
    test_an_old_sidecar_is_the_house_convention();
    test_a_16_bit_capture_must_state_its_full_scale();
    test_the_format_string_is_the_fallback();
    test_the_sidecar_path_rule();
    test_the_corpora_on_disk();
    return check_report("what a capture says about its own bytes");
}
