#!/usr/bin/env python3
"""Emit build/viewer_page.h from the files under web/ -- the page a person
edits, turned into the C string a compiler links in.

Ticket 13 (`.scratch/web-visualization/issues/13-*`) is the "why": the page
used to be 307 hand-escaped adjacent string literals in `src/viewer_page.h`,
where a forgotten `\\n` silently joins two lines of JavaScript and a `//`
comment then comments out everything after it -- a real failure mode of
that exact format, not a hypothetical. Nothing is substituted here beyond
one marker (see below); the page is static and every value it shows arrives
over the WebSocket, so these are assets, not a template, and no
substitution syntax should be added for a need nobody has.

Two files today, in a fixed, explicit order -- not a glob, and not implied
by filenames, which is what ticket 14's later split into lib/, wire.js and
views/*.js will need to keep meaning something as more files join it:

  web/viewer.html   the page: doctype, <style>, the markup, and a
                    `<script>` tag holding one marker line
  web/viewer.js      what fills that marker

The marker is a JavaScript comment, `/*BUILD:SCRIPT*/`, so it is inert if
ever viewed unprocessed and unambiguous to search for -- an HTML comment
would be parsed specially inside a `<script>` tag by old browsers' comment
compatibility rules, which is exactly the kind of surprise this generator
exists to avoid re-introducing.

Usage:

    python3 scripts/embed_web.py web/viewer.html build/viewer_page.h

Reads files, writes one header. No network, no receiver, runs anywhere
`make check` runs.
"""
import os
import re
import sys

SCRIPT_MARKER = "/*BUILD:SCRIPT*/"
GUARD = "VIEWER_PAGE_H"
NAME = "VIEWER_PAGE_HTML"

# Dependency order, stated once, here rather than implied by a directory
# listing (ticket 14) -- lib/ before wire.js before views/ before
# viewer.js, which is the only file with top-level executable statements
# (the final `connect();`) and so has to come last. Function declarations
# are hoisted and top-level `const`s only run before the first message
# ever arrives, so nothing here is load-bearing for *correctness* today --
# it is load-bearing for a reader, which is the same reason CLAUDE.md
# calls a hand-kept, drifting list worse than an explicit one.
JS_ORDER = [
    "lib/format.js",
    "lib/chart.js",
    "lib/table.js",
    "wire.js",
    "views/scope.js",
    "views/survey.js",
    "viewer.js",
]

HEADER_COMMENT = """/*
 * GENERATED by scripts/embed_web.py from web/ -- do not edit this file.
 * Edit web/viewer.html and web/viewer.js (or, after ticket 14's later
 * phases, whichever file under web/lib, web/wire.js or web/views actually
 * holds the line) and run `make` again.
 *
 * The Viewer, in the ticket's own words: "Canvas, no framework, no CDN."
 * Served whole by viewer_link.c for any GET that is not a WebSocket
 * upgrade; the browser's copy of the wire format lives in web/ beside the
 * page rather than in a shared header, because nothing else reads it in C
 * -- viewer_link.c only ever writes this format, never parses it back.
 *
 * Declines to draw a message stamped with a tuning generation older than
 * the newest `receiver_state` it holds (ADR-0027): the one rule this page
 * exists to prove, alongside the rule it cannot help but demonstrate just
 * by working at all -- a State update is replaceable, so this reconnects
 * and keeps showing whatever is newest rather than a growing backlog.
 *
 * The Health panel (ticket 08) shows what `link_health` carries -- the
 * per-stream sent/dropped counts and the send-queue high-water mark, both
 * facts only the server can know -- alongside two this page computes about
 * itself: received bytes/sec (it already timestamps and sizes every
 * message it decodes) and its own JS main-thread busy time. That second
 * one is ticket 05's honest gap closed rather than argued around: nothing
 * in a browser tab exposes its own OS CPU accounting to its own JS, so
 * this does not pretend to read one. It measures the fraction of each
 * rolling second actually spent inside this page's own message handling
 * and drawing, which is a real number about this page rather than a
 * guess at what an external profiler would have said -- and unlike a
 * one-off measurement taken from outside, it is what every Viewer, in
 * every browser, reports for as long as it runs.
 */
"""


def escape_line(line):
    """One source line as one C string literal: `"...\\n"`.

    Backslash and double-quote are escaped; everything else -- including a
    raw UTF-8 multi-byte character such as the survey mark glyphs -- passes
    through unchanged, since this file and the generated header are both
    read as UTF-8 and gcc stores a string literal's bytes as it finds them.
    Kept one literal per source line rather than emitted as one giant
    literal, so a compiler error still points at a recognisable place
    (C99's per-literal length limit is 4095 characters; this file's longest
    line is nowhere near it, but the shape is the same reason it was chosen
    originally).
    """
    escaped = line.replace("\\", "\\\\").replace('"', '\\"')
    return '"' + escaped + '\\n"'


def emit_header(path, page_text):
    lines = page_text.split("\n")
    # split() on text ending in "\n" yields a trailing "" -- the marker for
    # "nothing after the last real line", not a 309th empty line to emit.
    if lines and lines[-1] == "":
        lines.pop()
    with open(path, "w", encoding="utf-8") as f:
        f.write("#ifndef %s\n#define %s\n\n" % (GUARD, GUARD))
        f.write(HEADER_COMMENT)
        f.write("static const char %s[] =\n" % NAME)
        for line in lines:
            f.write(escape_line(line) + "\n")
        f.write(";\n\n#endif\n")


def main(argv):
    # `--list web/viewer.html` prints every source file this build depends
    # on (the HTML, then each JS_ORDER entry), one per line, relative to
    # the HTML file's own directory. The Makefile calls this to build
    # `viewer_page.h`'s prerequisite list from `JS_ORDER` itself rather
    # than keeping a second, hand-maintained copy of the same file set --
    # two lists of "every file this page depends on" is exactly the
    # `version.h`-outside-`APP_HDR` staleness shape this ticket's own
    # header comment warns about, just moved one file over.
    if len(argv) == 3 and argv[1] == "--list":
        html_path = argv[2]
        web_dir = os.path.dirname(html_path)
        print(html_path)
        for name in JS_ORDER:
            print(os.path.join(web_dir, name))
        return 0

    if len(argv) != 3:
        sys.stderr.write("usage: %s web/viewer.html build/viewer_page.h\n"
                          "       %s --list web/viewer.html\n" %
                          (argv[0], argv[0]))
        return 2
    html_path, out_path = argv[1], argv[2]
    web_dir = os.path.dirname(os.path.abspath(html_path))

    with open(html_path, encoding="utf-8") as f:
        html = f.read()

    # The marker sits alone on its own line, so what is replaced is the
    # marker *and* the newline that follows it: each web/*.js file already
    # ends in its own trailing newline, and splicing that in whole is what
    # reproduces the original page's "<script>\n<js>\n</script>" shape
    # exactly rather than reasoning about how many newlines to re-add.
    needle = SCRIPT_MARKER + "\n"
    if html.count(needle) != 1:
        sys.stderr.write(
            "%s: expected exactly one %s marker on its own line, found %d\n" %
            (html_path, SCRIPT_MARKER, html.count(needle)))
        return 1

    js_parts = []
    for name in JS_ORDER:
        with open(os.path.join(web_dir, name), encoding="utf-8") as f:
            content = f.read()
        if not content.endswith("\n"):
            sys.stderr.write("%s: must end with a newline\n" % name)
            return 1
        js_parts.append(content)
    script = "".join(js_parts)

    page = html.replace(needle, script)

    out_dir = os.path.dirname(out_path)
    if out_dir:
        os.makedirs(out_dir, exist_ok=True)
    emit_header(out_path, page)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
