#ifndef VIEWER_PAGE_H
#define VIEWER_PAGE_H

/*
 * The Viewer, in the ticket's own words: "Canvas, no framework, no CDN."
 * Served whole by viewer_link.c for any GET that is not a WebSocket
 * upgrade; the browser's copy of the wire format lives here beside the
 * page rather than in a shared header, because nothing else reads it in C
 * -- viewer_link.c only ever writes this format, never parses it back.
 *
 * Declines to draw a message stamped with a tuning generation older than
 * the newest `receiver_state` it holds (ADR-0027): the one rule this page
 * exists to prove, alongside the rule it cannot help but demonstrate just
 * by working at all -- a State update is replaceable, so this reconnects
 * and keeps showing whatever is newest rather than a growing backlog.
 *
 * The Health panel (ticket 08) shows what `link_health` carries -- the
 * per-stream sent/dropped counts and the send-queue high-water mark, both
 * facts only the server can know -- alongside two this page computes about
 * itself: received bytes/sec (it already timestamps and sizes every
 * message it decodes) and its own JS main-thread busy time. That second
 * one is ticket 05's honest gap closed rather than argued around: nothing
 * in a browser tab exposes its own OS CPU accounting to its own JS, so
 * this does not pretend to read one. It measures the fraction of each
 * rolling second actually spent inside this page's own message handling
 * and drawing, which is a real number about this page rather than a
 * guess at what an external profiler would have said -- and unlike a
 * one-off measurement taken from outside, it is what every Viewer, in
 * every browser, reports for as long as it runs.
 */
static const char VIEWER_PAGE_HTML[] =
"<!doctype html><title>sdrprobe Viewer</title>\n"
"<style>\n"
"  body { background:#0c131c; color:#c7d3dc; font:14px monospace; margin:0; padding:16px; }\n"
"  h1 { font-size:16px; color:#e8edf0; margin:0 0 10px; }\n"
"  #hud { margin-bottom:10px; color:#5adca4; }\n"
"  #hud .stale { color:#ff6864; }\n"
"  canvas { display:block; background:#0a0f16; margin-bottom:14px; max-width:100%; }\n"
"  .label { color:#8291a0; margin:4px 0; }\n"
"  #health { margin:10px 0 14px; color:#8291a0; border-top:1px solid #232f3b; padding-top:8px; }\n"
"  #health span { color:#c7d3dc; }\n"
"  #health .row { margin:2px 0; }\n"
"  #tabs { margin-bottom:14px; }\n"
"  #tabs button { background:#16202c; color:#8291a0; border:1px solid #232f3b; font:14px monospace; padding:6px 16px; cursor:pointer; }\n"
"  #tabs button.active { background:#1d3b3a; color:#5adca4; border-color:#2e5a58; }\n"
"  table { border-collapse:collapse; width:100%; margin-bottom:14px; }\n"
"  th, td { text-align:left; padding:3px 10px 3px 0; font:13px monospace; }\n"
"  th { color:#8291a0; border-bottom:1px solid #232f3b; }\n"
"  td { color:#c7d3dc; }\n"
"  .mark-signal { color:#5adcc8; }\n"
"  .mark-empty { color:#8291a0; }\n"
"  .mark-receiver { color:#ff9b64; }\n"
"  .mark-contested { color:#ff6864; }\n"
"</style>\n"
"<h1>sdrprobe -- live Viewer</h1>\n"
"<div id=\"tabs\">\n"
"  <button id=\"tab-scope\" class=\"active\">Scope</button>\n"
"  <button id=\"tab-survey\">Survey</button>\n"
"</div>\n"
"<div id=\"hud\">connecting...</div>\n"
"<div id=\"panel-scope\">\n"
"  <div class=\"label\">spectrum (average: cyan, peak hold: orange)</div>\n"
"  <canvas id=\"spectrum\" width=\"900\" height=\"260\"></canvas>\n"
"  <div class=\"label\">waterfall (built from rows in this browser; never re-sent)</div>\n"
"  <canvas id=\"waterfall\" width=\"900\" height=\"200\"></canvas>\n"
"</div>\n"
"<div id=\"panel-survey\" hidden>\n"
"  <div class=\"label\" id=\"survey-status\">no sweep yet</div>\n"
"  <canvas id=\"survey-chart\" width=\"900\" height=\"260\"></canvas>\n"
"  <div class=\"label\">candidates (<span id=\"survey-count\">0</span>)</div>\n"
"  <table>\n"
"    <thead><tr><th></th><th>frequency</th><th>level</th><th>width</th><th>shape</th></tr></thead>\n"
"    <tbody id=\"survey-rows\"></tbody>\n"
"  </table>\n"
"</div>\n"
"<div class=\"label\">link health</div>\n"
"<div id=\"health\">awaiting link_health...</div>\n"
"<script>\n"
"(function(){\n"
"  const hud = document.getElementById('hud');\n"
"  const health = document.getElementById('health');\n"
"  const specCanvas = document.getElementById('spectrum');\n"
"  const specCtx = specCanvas.getContext('2d');\n"
"  const wfCanvas = document.getElementById('waterfall');\n"
"  const wfCtx = wfCanvas.getContext('2d');\n"
"  const surveyChart = document.getElementById('survey-chart');\n"
"  const surveyCtx = surveyChart.getContext('2d');\n"
"  const surveyStatus = document.getElementById('survey-status');\n"
"  const surveyCount = document.getElementById('survey-count');\n"
"  const surveyRows = document.getElementById('survey-rows');\n"
"  const panelScope = document.getElementById('panel-scope');\n"
"  const panelSurvey = document.getElementById('panel-survey');\n"
"  const tabScope = document.getElementById('tab-scope');\n"
"  const tabSurvey = document.getElementById('tab-survey');\n"
"\n"
"  let latestGeneration = 0; // the newest tuning_generation receiver_state has named\n"
"  let sent = 0, dropped = 0; // this Viewer's own count of what it drew vs discarded\n"
"  let ws = null; // module-scope so the tab buttons can send on it\n"
"\n"
"  // Ticket 07: which tab is showing, and which the server has confirmed.\n"
"  // The click switches the panel at once -- a browser waiting a round\n"
"  // trip to redraw a button press reads as broken -- and `receiver_state`\n"
"  // corrects it afterwards if the two ever disagree (another Viewer\n"
"  // switching it, or this page reconnecting mid-session with no `view`\n"
"  // of its own yet sent). 0 is TAB_SURVEY, 1 is TAB_SCOPE\n"
"  // (input_route.h's enum active_tab), matched here rather than\n"
"  // reinvented, since receiver_state.tab is that enum's own int.\n"
"  function showTab(tab) {\n"
"    const survey = tab === 0;\n"
"    panelScope.hidden = survey;\n"
"    panelSurvey.hidden = !survey;\n"
"    tabScope.classList.toggle('active', !survey);\n"
"    tabSurvey.classList.toggle('active', survey);\n"
"  }\n"
"  tabScope.onclick = () => { showTab(1); if (ws) ws.send('view scope'); };\n"
"  tabSurvey.onclick = () => { showTab(0); if (ws) ws.send('view survey'); };\n"
"\n"
"  // Ticket 08's Health panel: what this page can measure about itself\n"
"  // (received bytes/sec, its own JS busy time), rolled up once a second\n"
"  // alongside whatever link_health last reported about the server side.\n"
"  let lastHealth = null;\n"
"  let bytesThisWindow = 0, throughputBps = 0;\n"
"  let busyMs = 0, windowStart = performance.now(), jsBusyPercent = 0;\n"
"  setInterval(() => {\n"
"    const now = performance.now();\n"
"    const elapsed = now - windowStart;\n"
"    jsBusyPercent = elapsed > 0 ? (100 * busyMs / elapsed) : 0;\n"
"    throughputBps = elapsed > 0 ? (bytesThisWindow * 1000 / elapsed) : 0;\n"
"    busyMs = 0; bytesThisWindow = 0; windowStart = now;\n"
"    renderHealth();\n"
"  }, 1000);\n"
"\n"
"  function connect() {\n"
"    // ADR-0027's amendment (2026-09-17): whatever query string loaded\n"
"    // this page -- '?token=...', once the server was started with\n"
"    // --serve-bind beyond loopback -- is forwarded onto the socket's\n"
"    // own path unchanged, since the same string satisfies the same\n"
"    // check there. location.search is '' when there is none, so a\n"
"    // token-free server is unaffected.\n"
"    ws = new WebSocket('ws://' + location.host + '/viewer' + location.search);\n"
"    ws.binaryType = 'arraybuffer';\n"
"    ws.onopen = () => {\n"
"      ws.send('subscribe spectrum waterfall receiver_state link_health survey_spectrum survey_state');\n"
"      hud.textContent = 'connected, awaiting receiver state...';\n"
"    };\n"
"    ws.onclose = () => { hud.textContent = 'disconnected -- retrying...'; setTimeout(connect, 1000); };\n"
"    ws.onerror = () => ws.close();\n"
"    ws.onmessage = (ev) => {\n"
"      // Busy time and received bytes are this page's own two Health\n"
"      // fields (ticket 08); the try/finally means every exit path below\n"
"      // -- the early 'stale generation' return included -- is timed the\n"
"      // same way, rather than each needing its own bookkeeping line.\n"
"      const t0 = performance.now();\n"
"      try {\n"
"        bytesThisWindow += (typeof ev.data === 'string') ? ev.data.length : ev.data.byteLength;\n"
"        if (typeof ev.data === 'string') { handleState(JSON.parse(ev.data)); return; }\n"
"        const view = new DataView(ev.data);\n"
"        const type = view.getUint8(1);\n"
"        const generation = view.getUint32(4, true);\n"
"        const bins = view.getUint32(16, true);\n"
"        if (generation < latestGeneration) { dropped++; return; } // ADR-0027\n"
"        sent++;\n"
"        if (type === 1) { // spectrum: bins average, then bins peak\n"
"          const average = new Float32Array(ev.data, 20, bins);\n"
"          const peak = new Float32Array(ev.data, 20 + bins * 4, bins);\n"
"          drawSpectrum(average, peak);\n"
"        } else if (type === 2) { // waterfall_row: bins of one row\n"
"          drawWaterfall(new Float32Array(ev.data, 20, bins));\n"
"        } else if (type === 3) { // survey_spectrum: ticket 07's wider header\n"
"          const lowerHz = view.getUint32(20, true);\n"
"          const upperHz = view.getUint32(24, true);\n"
"          const power = new Float32Array(ev.data, 28, bins);\n"
"          drawSurveyChart(lowerHz, upperHz, power);\n"
"        }\n"
"      } finally {\n"
"        busyMs += performance.now() - t0;\n"
"      }\n"
"    };\n"
"  }\n"
"\n"
"  function handleState(state) {\n"
"    // Stored, not rendered here: link_health arrives up to once per\n"
"    // server block (tens of times a second), and a full innerHTML\n"
"    // rebuild on every one of them is JS busy time this page does not\n"
"    // need to spend -- the once-a-second interval below already redraws\n"
"    // the panel, and spending less time here is less time not reading\n"
"    // the socket, which is less backpressure this page itself causes.\n"
"    if (state.type === 'link_health') { lastHealth = state; return; }\n"
"    if (state.type === 'survey_state') { renderSurveyState(state); return; }\n"
"    if (state.type !== 'receiver_state') return;\n"
"    latestGeneration = state.tuning_generation;\n"
"    showTab(state.tab); // corrects a click sent before the server answered,\n"
"                        // and reflects another Viewer's own switch\n"
"    hud.innerHTML = 'center ' + (state.center_hz / 1e6).toFixed(6) + ' MHz &nbsp; '\n"
"      + 'rate ' + (state.sample_rate_hz / 1e6).toFixed(3) + ' MS/s &nbsp; '\n"
"      + 'ppm ' + state.ppm + ' &nbsp; '\n"
"      + 'generation ' + state.tuning_generation + ' &nbsp; '\n"
"      + 'drawn ' + sent + ' declined ' + dropped;\n"
"  }\n"
"\n"
"  // Ticket 07's Survey tab: the status line, the candidate table, and the\n"
"  // marks the next survey_spectrum message draws over the trace. `mark`\n"
"  // is sdrgui_survey_peak_mark()'s own enum, named here rather than\n"
"  // reinterpreting the flag word the server already decided from --\n"
"  // 0 signal, 1 empty, 2 receiver-like, 3 contested (sdrgui.h).\n"
"  const MARK_CLASS = ['mark-signal', 'mark-empty', 'mark-receiver', 'mark-contested'];\n"
"  const MARK_GLYPH = ['\u25cf', '\u25cb', '\u2715', '\u2715'];\n"
"  let lastCandidates = [];\n"
"\n"
"  function renderSurveyState(state) {\n"
"    surveyStatus.textContent = state.status;\n"
"    surveyCount.textContent = state.candidate_count;\n"
"    lastCandidates = state.candidates || [];\n"
"    surveyRows.innerHTML = lastCandidates.map((c) => {\n"
"      const cls = MARK_CLASS[c.mark] || 'mark-signal';\n"
"      const glyph = MARK_GLYPH[c.mark] || '?';\n"
"      return '<tr><td class=\"' + cls + '\">' + glyph + '</td>'\n"
"        + '<td>' + (c.hz / 1e6).toFixed(4) + ' MHz</td>'\n"
"        + '<td>' + c.power_dbfs.toFixed(1) + ' dBFS</td>'\n"
"        + '<td>' + (c.has_carrier ? Math.round(c.width_hz / 1e3) + ' kHz' : '-') + '</td>'\n"
"        + '<td>' + (c.has_carrier ? c.shape : '-') + '</td></tr>';\n"
"    }).join('');\n"
"  }\n"
"\n"
"  // Per-stream sent/dropped/high-water are the server's own facts about\n"
"  // this connection (nothing else could report a dropped message, since\n"
"  // it never reaches here); received throughput and JS busy% are this\n"
"  // page's own two, both rolled into the same panel.\n"
"  function renderHealth() {\n"
"    const h = lastHealth;\n"
"    const dropRate = (s, d) => (s + d) > 0 ? (100 * d / (s + d)).toFixed(1) : '0.0';\n"
"    if (!h) { health.textContent = 'awaiting link_health...'; return; }\n"
"    health.innerHTML =\n"
"      '<div class=\"row\">spectrum sent <span>' + h.spectrum_sent + '</span> dropped <span>'\n"
"        + h.spectrum_dropped + '</span> (<span>' + dropRate(h.spectrum_sent, h.spectrum_dropped) + '%</span>)</div>'\n"
"      + '<div class=\"row\">waterfall sent <span>' + h.waterfall_sent + '</span> dropped <span>'\n"
"        + h.waterfall_dropped + '</span> (<span>' + dropRate(h.waterfall_sent, h.waterfall_dropped) + '%</span>)</div>'\n"
"      + '<div class=\"row\">receiver_state sent <span>' + h.receiver_state_sent + '</span> dropped <span>'\n"
"        + h.receiver_state_dropped + '</span></div>'\n"
"      + '<div class=\"row\">send-queue high-water <span>' + formatBytes(h.send_queue_high_water) + '</span></div>'\n"
"      + '<div class=\"row\">received <span>' + formatBitsPerSecond(throughputBps) + '</span> (this tab)</div>'\n"
"      + '<div class=\"row\">server CPU <span>' + h.server_cpu_percent.toFixed(1) + '%</span></div>'\n"
"      + '<div class=\"row\">this tab, JS busy <span>' + jsBusyPercent.toFixed(1) + '%</span></div>';\n"
"  }\n"
"\n"
"  // Decimal SI throughout (AGENTS.md's units convention): a byte count is\n"
"  // KB/MB at 1000/1e6, a throughput is Kbps/Mbps -- bits, not bytes, at\n"
"  // the same decimal scale -- never KiB/MiB, never a silent /1024 behind\n"
"  // a \"KB\" label.\n"
"  function formatBytes(n) {\n"
"    if (n >= 1e6) return (n / 1e6).toFixed(2) + ' MB';\n"
"    return (n / 1e3).toFixed(1) + ' KB';\n"
"  }\n"
"  function formatBitsPerSecond(bytesPerSecond) {\n"
"    const bits = bytesPerSecond * 8;\n"
"    if (bits >= 1e6) return (bits / 1e6).toFixed(2) + ' Mbps';\n"
"    return (bits / 1e3).toFixed(1) + ' Kbps';\n"
"  }\n"
"\n"
"  function dbfsToY(v, height) {\n"
"    const top = 0, bottom = -120; // SPECTRUM_TOP_DBFS and the floor this page assumes\n"
"    const clamped = Math.max(bottom, Math.min(top, v));\n"
"    return height * (top - clamped) / (top - bottom);\n"
"  }\n"
"\n"
"  function drawSpectrum(average, peak) {\n"
"    const w = specCanvas.width, h = specCanvas.height;\n"
"    specCtx.fillStyle = '#0a0f16';\n"
"    specCtx.fillRect(0, 0, w, h);\n"
"    plot(peak, '#e8a355');\n"
"    plot(average, '#5adcc8');\n"
"    function plot(bins, color) {\n"
"      specCtx.strokeStyle = color;\n"
"      specCtx.beginPath();\n"
"      for (let x = 0; x < w; x++) {\n"
"        const i = Math.floor(x * bins.length / w);\n"
"        const y = dbfsToY(bins[i], h);\n"
"        if (x === 0) specCtx.moveTo(x, y); else specCtx.lineTo(x, y);\n"
"      }\n"
"      specCtx.stroke();\n"
"    }\n"
"  }\n"
"\n"
"  // Ticket 07's Survey chart: the same dBFS-to-y mapping the Scope's\n"
"  // spectrum uses, over the swept range instead of one block's -- and a\n"
"  // mark above the trace at each candidate's own frequency, reading\n"
"  // `lastCandidates` from whichever survey_state arrived last rather\n"
"  // than recomputing anything the server already decided.\n"
"  function drawSurveyChart(lowerHz, upperHz, power) {\n"
"    const w = surveyChart.width, h = surveyChart.height;\n"
"    const span = upperHz - lowerHz;\n"
"    surveyCtx.fillStyle = '#0a0f16';\n"
"    surveyCtx.fillRect(0, 0, w, h);\n"
"    surveyCtx.strokeStyle = '#5adcc8';\n"
"    surveyCtx.beginPath();\n"
"    for (let x = 0; x < w; x++) {\n"
"      const i = Math.floor(x * power.length / w);\n"
"      const y = dbfsToY(power[i], h);\n"
"      if (x === 0) surveyCtx.moveTo(x, y); else surveyCtx.lineTo(x, y);\n"
"    }\n"
"    surveyCtx.stroke();\n"
"    if (span > 0) {\n"
"      for (const c of lastCandidates) {\n"
"        const x = Math.round(w * (c.hz - lowerHz) / span);\n"
"        if (x < 0 || x > w) continue;\n"
"        surveyCtx.fillStyle = ['#5adcc8', '#8291a0', '#ff9b64', '#ff6864'][c.mark] || '#5adcc8';\n"
"        surveyCtx.beginPath();\n"
"        surveyCtx.arc(x, dbfsToY(c.power_dbfs, h) - 6, 3, 0, 2 * Math.PI);\n"
"        surveyCtx.fill();\n"
"      }\n"
"      surveyCtx.fillStyle = '#8291a0';\n"
"      surveyCtx.font = '12px monospace';\n"
"      surveyCtx.fillText((lowerHz / 1e6).toFixed(3) + ' MHz', 4, h - 4);\n"
"      const upperLabel = (upperHz / 1e6).toFixed(3) + ' MHz';\n"
"      surveyCtx.fillText(upperLabel, w - 8 * upperLabel.length, h - 4);\n"
"    }\n"
"  }\n"
"\n"
"  function colorFor(dbfs) {\n"
"    const t = Math.max(0, Math.min(1, (dbfs + 100) / 90));\n"
"    const r = Math.round(20 + 220 * t), g = Math.round(30 + 140 * t), b = Math.round(50 + 60 * (1 - t));\n"
"    return 'rgb(' + r + ',' + g + ',' + b + ')';\n"
"  }\n"
"\n"
"  // Scrolls the existing image down by one row and draws only the new\n"
"  // one at the top, rather than redrawing all `h` rows from the row\n"
"  // history every time one more arrives -- the canvas itself is the\n"
"  // history now, which is also why this page no longer keeps one of its\n"
"  // own. Measured against the whole-redraw version this replaced: it\n"
"  // was 95%+ of this page's own JS busy time and growing as history\n"
"  // filled (drawImage's one call against up to `w * h` -- 900 * 200 --\n"
"  // individual fillRect calls per row).\n"
"  function drawWaterfall(row) {\n"
"    const w = wfCanvas.width, h = wfCanvas.height;\n"
"    wfCtx.drawImage(wfCanvas, 0, 0, w, h - 1, 0, 1, w, h - 1);\n"
"    for (let x = 0; x < w; x++) {\n"
"      const i = Math.floor(x * row.length / w);\n"
"      wfCtx.fillStyle = colorFor(row[i]);\n"
"      wfCtx.fillRect(x, 0, 1, 1);\n"
"    }\n"
"  }\n"
"\n"
"  connect();\n"
"})();\n"
"</script>\n";

#endif
