#ifndef VIEWER_PAGE_H
#define VIEWER_PAGE_H

/*
 * The Viewer, in the ticket's own words: "Canvas, no framework, no CDN."
 * Served whole by viewer_link.c for any GET that is not a WebSocket
 * upgrade; the browser's copy of the wire format lives here beside the
 * page rather than in a shared header, because nothing else reads it in C
 * -- viewer_link.c only ever writes this format, never parses it back.
 *
 * Declines to draw a message stamped with a tuning generation older than
 * the newest `receiver_state` it holds (ADR-0027): the one rule this page
 * exists to prove, alongside the rule it cannot help but demonstrate just
 * by working at all -- a State update is replaceable, so this reconnects
 * and keeps showing whatever is newest rather than a growing backlog.
 */
static const char VIEWER_PAGE_HTML[] =
"<!doctype html><title>sdrprobe Viewer</title>\n"
"<style>\n"
"  body { background:#0c131c; color:#c7d3dc; font:14px monospace; margin:0; padding:16px; }\n"
"  h1 { font-size:16px; color:#e8edf0; margin:0 0 10px; }\n"
"  #hud { margin-bottom:10px; color:#5adca4; }\n"
"  #hud .stale { color:#ff6864; }\n"
"  canvas { display:block; background:#0a0f16; margin-bottom:14px; max-width:100%; }\n"
"  .label { color:#8291a0; margin:4px 0; }\n"
"</style>\n"
"<h1>sdrprobe -- live Viewer</h1>\n"
"<div id=\"hud\">connecting...</div>\n"
"<div class=\"label\">spectrum (average: cyan, peak hold: orange)</div>\n"
"<canvas id=\"spectrum\" width=\"900\" height=\"260\"></canvas>\n"
"<div class=\"label\">waterfall (built from rows in this browser; never re-sent)</div>\n"
"<canvas id=\"waterfall\" width=\"900\" height=\"200\"></canvas>\n"
"<script>\n"
"(function(){\n"
"  const hud = document.getElementById('hud');\n"
"  const specCanvas = document.getElementById('spectrum');\n"
"  const specCtx = specCanvas.getContext('2d');\n"
"  const wfCanvas = document.getElementById('waterfall');\n"
"  const wfCtx = wfCanvas.getContext('2d');\n"
"  const wfHistory = []; // oldest first; each entry is a Float32Array of dBFS\n"
"  const WF_ROWS_MAX = wfCanvas.height;\n"
"\n"
"  let latestGeneration = 0; // the newest tuning_generation receiver_state has named\n"
"  let sent = 0, dropped = 0; // this Viewer's own count of what it drew vs discarded\n"
"\n"
"  function connect() {\n"
"    const ws = new WebSocket('ws://' + location.host + '/viewer');\n"
"    ws.binaryType = 'arraybuffer';\n"
"    ws.onopen = () => {\n"
"      ws.send('subscribe spectrum waterfall receiver_state');\n"
"      hud.textContent = 'connected, awaiting receiver state...';\n"
"    };\n"
"    ws.onclose = () => { hud.textContent = 'disconnected -- retrying...'; setTimeout(connect, 1000); };\n"
"    ws.onerror = () => ws.close();\n"
"    ws.onmessage = (ev) => {\n"
"      if (typeof ev.data === 'string') { handleState(JSON.parse(ev.data)); return; }\n"
"      const view = new DataView(ev.data);\n"
"      const type = view.getUint8(1);\n"
"      const generation = view.getUint32(4, true);\n"
"      const bins = view.getUint32(16, true);\n"
"      if (generation < latestGeneration) { dropped++; return; } // ADR-0027\n"
"      sent++;\n"
"      if (type === 1) { // spectrum: bins average, then bins peak\n"
"        const average = new Float32Array(ev.data, 20, bins);\n"
"        const peak = new Float32Array(ev.data, 20 + bins * 4, bins);\n"
"        drawSpectrum(average, peak);\n"
"      } else if (type === 2) { // waterfall_row: bins of one row\n"
"        const row = new Float32Array(ev.data, 20, bins).slice();\n"
"        wfHistory.push(row);\n"
"        if (wfHistory.length > WF_ROWS_MAX) wfHistory.shift();\n"
"        drawWaterfall();\n"
"      }\n"
"    };\n"
"  }\n"
"\n"
"  function handleState(state) {\n"
"    if (state.type !== 'receiver_state') return;\n"
"    latestGeneration = state.tuning_generation;\n"
"    hud.innerHTML = 'center ' + (state.center_hz / 1e6).toFixed(6) + ' MHz &nbsp; '\n"
"      + 'rate ' + (state.sample_rate_hz / 1e6).toFixed(3) + ' MS/s &nbsp; '\n"
"      + 'ppm ' + state.ppm + ' &nbsp; '\n"
"      + 'generation ' + state.tuning_generation + ' &nbsp; '\n"
"      + 'drawn ' + sent + ' declined ' + dropped;\n"
"  }\n"
"\n"
"  function dbfsToY(v, height) {\n"
"    const top = 0, bottom = -120; // SPECTRUM_TOP_DBFS and the floor this page assumes\n"
"    const clamped = Math.max(bottom, Math.min(top, v));\n"
"    return height * (top - clamped) / (top - bottom);\n"
"  }\n"
"\n"
"  function drawSpectrum(average, peak) {\n"
"    const w = specCanvas.width, h = specCanvas.height;\n"
"    specCtx.fillStyle = '#0a0f16';\n"
"    specCtx.fillRect(0, 0, w, h);\n"
"    plot(peak, '#e8a355');\n"
"    plot(average, '#5adcc8');\n"
"    function plot(bins, color) {\n"
"      specCtx.strokeStyle = color;\n"
"      specCtx.beginPath();\n"
"      for (let x = 0; x < w; x++) {\n"
"        const i = Math.floor(x * bins.length / w);\n"
"        const y = dbfsToY(bins[i], h);\n"
"        if (x === 0) specCtx.moveTo(x, y); else specCtx.lineTo(x, y);\n"
"      }\n"
"      specCtx.stroke();\n"
"    }\n"
"  }\n"
"\n"
"  function colorFor(dbfs) {\n"
"    const t = Math.max(0, Math.min(1, (dbfs + 100) / 90));\n"
"    const r = Math.round(20 + 220 * t), g = Math.round(30 + 140 * t), b = Math.round(50 + 60 * (1 - t));\n"
"    return 'rgb(' + r + ',' + g + ',' + b + ')';\n"
"  }\n"
"\n"
"  function drawWaterfall() {\n"
"    const w = wfCanvas.width, h = wfCanvas.height;\n"
"    wfCtx.fillStyle = '#0a0f16';\n"
"    wfCtx.fillRect(0, 0, w, h);\n"
"    for (let r = 0; r < wfHistory.length; r++) {\n"
"      const row = wfHistory[wfHistory.length - 1 - r]; // newest at the top\n"
"      for (let x = 0; x < w; x++) {\n"
"        const i = Math.floor(x * row.length / w);\n"
"        wfCtx.fillStyle = colorFor(row[i]);\n"
"        wfCtx.fillRect(x, r, 1, 1);\n"
"      }\n"
"    }\n"
"  }\n"
"\n"
"  connect();\n"
"})();\n"
"</script>\n";

#endif
