#ifndef VIEWER_PAGE_H
#define VIEWER_PAGE_H

/*
 * The Viewer, in the ticket's own words: "Canvas, no framework, no CDN."
 * Served whole by viewer_link.c for any GET that is not a WebSocket
 * upgrade; the browser's copy of the wire format lives here beside the
 * page rather than in a shared header, because nothing else reads it in C
 * -- viewer_link.c only ever writes this format, never parses it back.
 *
 * Declines to draw a message stamped with a tuning generation older than
 * the newest `receiver_state` it holds (ADR-0027): the one rule this page
 * exists to prove, alongside the rule it cannot help but demonstrate just
 * by working at all -- a State update is replaceable, so this reconnects
 * and keeps showing whatever is newest rather than a growing backlog.
 *
 * The Health panel (ticket 08) shows what `link_health` carries -- the
 * per-stream sent/dropped counts and the send-queue high-water mark, both
 * facts only the server can know -- alongside two this page computes about
 * itself: received bytes/sec (it already timestamps and sizes every
 * message it decodes) and its own JS main-thread busy time. That second
 * one is ticket 05's honest gap closed rather than argued around: nothing
 * in a browser tab exposes its own OS CPU accounting to its own JS, so
 * this does not pretend to read one. It measures the fraction of each
 * rolling second actually spent inside this page's own message handling
 * and drawing, which is a real number about this page rather than a
 * guess at what an external profiler would have said -- and unlike a
 * one-off measurement taken from outside, it is what every Viewer, in
 * every browser, reports for as long as it runs.
 */
static const char VIEWER_PAGE_HTML[] =
"<!doctype html><title>sdrprobe Viewer</title>\n"
"<style>\n"
"  body { background:#0c131c; color:#c7d3dc; font:14px monospace; margin:0; padding:16px; }\n"
"  h1 { font-size:16px; color:#e8edf0; margin:0 0 10px; }\n"
"  #hud { margin-bottom:10px; color:#5adca4; }\n"
"  #hud .stale { color:#ff6864; }\n"
"  canvas { display:block; background:#0a0f16; margin-bottom:14px; max-width:100%; }\n"
"  .label { color:#8291a0; margin:4px 0; }\n"
"  #health { margin:10px 0 14px; color:#8291a0; border-top:1px solid #232f3b; padding-top:8px; }\n"
"  #health span { color:#c7d3dc; }\n"
"  #health .row { margin:2px 0; }\n"
"</style>\n"
"<h1>sdrprobe -- live Viewer</h1>\n"
"<div id=\"hud\">connecting...</div>\n"
"<div class=\"label\">spectrum (average: cyan, peak hold: orange)</div>\n"
"<canvas id=\"spectrum\" width=\"900\" height=\"260\"></canvas>\n"
"<div class=\"label\">waterfall (built from rows in this browser; never re-sent)</div>\n"
"<canvas id=\"waterfall\" width=\"900\" height=\"200\"></canvas>\n"
"<div class=\"label\">link health</div>\n"
"<div id=\"health\">awaiting link_health...</div>\n"
"<script>\n"
"(function(){\n"
"  const hud = document.getElementById('hud');\n"
"  const health = document.getElementById('health');\n"
"  const specCanvas = document.getElementById('spectrum');\n"
"  const specCtx = specCanvas.getContext('2d');\n"
"  const wfCanvas = document.getElementById('waterfall');\n"
"  const wfCtx = wfCanvas.getContext('2d');\n"
"  const wfHistory = []; // oldest first; each entry is a Float32Array of dBFS\n"
"  const WF_ROWS_MAX = wfCanvas.height;\n"
"\n"
"  let latestGeneration = 0; // the newest tuning_generation receiver_state has named\n"
"  let sent = 0, dropped = 0; // this Viewer's own count of what it drew vs discarded\n"
"\n"
"  // Ticket 08's Health panel: what this page can measure about itself\n"
"  // (received bytes/sec, its own JS busy time), rolled up once a second\n"
"  // alongside whatever link_health last reported about the server side.\n"
"  let lastHealth = null;\n"
"  let bytesThisWindow = 0, throughputBps = 0;\n"
"  let busyMs = 0, windowStart = performance.now(), jsBusyPercent = 0;\n"
"  setInterval(() => {\n"
"    const now = performance.now();\n"
"    const elapsed = now - windowStart;\n"
"    jsBusyPercent = elapsed > 0 ? (100 * busyMs / elapsed) : 0;\n"
"    throughputBps = elapsed > 0 ? (bytesThisWindow * 1000 / elapsed) : 0;\n"
"    busyMs = 0; bytesThisWindow = 0; windowStart = now;\n"
"    renderHealth();\n"
"  }, 1000);\n"
"\n"
"  function connect() {\n"
"    const ws = new WebSocket('ws://' + location.host + '/viewer');\n"
"    ws.binaryType = 'arraybuffer';\n"
"    ws.onopen = () => {\n"
"      ws.send('subscribe spectrum waterfall receiver_state link_health');\n"
"      hud.textContent = 'connected, awaiting receiver state...';\n"
"    };\n"
"    ws.onclose = () => { hud.textContent = 'disconnected -- retrying...'; setTimeout(connect, 1000); };\n"
"    ws.onerror = () => ws.close();\n"
"    ws.onmessage = (ev) => {\n"
"      // Busy time and received bytes are this page's own two Health\n"
"      // fields (ticket 08); the try/finally means every exit path below\n"
"      // -- the early 'stale generation' return included -- is timed the\n"
"      // same way, rather than each needing its own bookkeeping line.\n"
"      const t0 = performance.now();\n"
"      try {\n"
"        bytesThisWindow += (typeof ev.data === 'string') ? ev.data.length : ev.data.byteLength;\n"
"        if (typeof ev.data === 'string') { handleState(JSON.parse(ev.data)); return; }\n"
"        const view = new DataView(ev.data);\n"
"        const type = view.getUint8(1);\n"
"        const generation = view.getUint32(4, true);\n"
"        const bins = view.getUint32(16, true);\n"
"        if (generation < latestGeneration) { dropped++; return; } // ADR-0027\n"
"        sent++;\n"
"        if (type === 1) { // spectrum: bins average, then bins peak\n"
"          const average = new Float32Array(ev.data, 20, bins);\n"
"          const peak = new Float32Array(ev.data, 20 + bins * 4, bins);\n"
"          drawSpectrum(average, peak);\n"
"        } else if (type === 2) { // waterfall_row: bins of one row\n"
"          const row = new Float32Array(ev.data, 20, bins).slice();\n"
"          wfHistory.push(row);\n"
"          if (wfHistory.length > WF_ROWS_MAX) wfHistory.shift();\n"
"          drawWaterfall();\n"
"        }\n"
"      } finally {\n"
"        busyMs += performance.now() - t0;\n"
"      }\n"
"    };\n"
"  }\n"
"\n"
"  function handleState(state) {\n"
"    // Stored, not rendered here: link_health arrives up to once per\n"
"    // server block (tens of times a second), and a full innerHTML\n"
"    // rebuild on every one of them is JS busy time this page does not\n"
"    // need to spend -- the once-a-second interval below already redraws\n"
"    // the panel, and spending less time here is less time not reading\n"
"    // the socket, which is less backpressure this page itself causes.\n"
"    if (state.type === 'link_health') { lastHealth = state; return; }\n"
"    if (state.type !== 'receiver_state') return;\n"
"    latestGeneration = state.tuning_generation;\n"
"    hud.innerHTML = 'center ' + (state.center_hz / 1e6).toFixed(6) + ' MHz &nbsp; '\n"
"      + 'rate ' + (state.sample_rate_hz / 1e6).toFixed(3) + ' MS/s &nbsp; '\n"
"      + 'ppm ' + state.ppm + ' &nbsp; '\n"
"      + 'generation ' + state.tuning_generation + ' &nbsp; '\n"
"      + 'drawn ' + sent + ' declined ' + dropped;\n"
"  }\n"
"\n"
"  // Per-stream sent/dropped/high-water are the server's own facts about\n"
"  // this connection (nothing else could report a dropped message, since\n"
"  // it never reaches here); received throughput and JS busy% are this\n"
"  // page's own two, both rolled into the same panel.\n"
"  function renderHealth() {\n"
"    const h = lastHealth;\n"
"    const dropRate = (s, d) => (s + d) > 0 ? (100 * d / (s + d)).toFixed(1) : '0.0';\n"
"    if (!h) { health.textContent = 'awaiting link_health...'; return; }\n"
"    health.innerHTML =\n"
"      '<div class=\"row\">spectrum sent <span>' + h.spectrum_sent + '</span> dropped <span>'\n"
"        + h.spectrum_dropped + '</span> (<span>' + dropRate(h.spectrum_sent, h.spectrum_dropped) + '%</span>)</div>'\n"
"      + '<div class=\"row\">waterfall sent <span>' + h.waterfall_sent + '</span> dropped <span>'\n"
"        + h.waterfall_dropped + '</span> (<span>' + dropRate(h.waterfall_sent, h.waterfall_dropped) + '%</span>)</div>'\n"
"      + '<div class=\"row\">receiver_state sent <span>' + h.receiver_state_sent + '</span> dropped <span>'\n"
"        + h.receiver_state_dropped + '</span></div>'\n"
"      + '<div class=\"row\">send-queue high-water <span>' + formatBytes(h.send_queue_high_water) + '</span></div>'\n"
"      + '<div class=\"row\">received <span>' + formatBitsPerSecond(throughputBps) + '</span> (this tab)</div>'\n"
"      + '<div class=\"row\">server CPU <span>' + h.server_cpu_percent.toFixed(1) + '%</span></div>'\n"
"      + '<div class=\"row\">this tab, JS busy <span>' + jsBusyPercent.toFixed(1) + '%</span></div>';\n"
"  }\n"
"\n"
"  // Decimal SI throughout (AGENTS.md's units convention): a byte count is\n"
"  // KB/MB at 1000/1e6, a throughput is Kbps/Mbps -- bits, not bytes, at\n"
"  // the same decimal scale -- never KiB/MiB, never a silent /1024 behind\n"
"  // a \"KB\" label.\n"
"  function formatBytes(n) {\n"
"    if (n >= 1e6) return (n / 1e6).toFixed(2) + ' MB';\n"
"    return (n / 1e3).toFixed(1) + ' KB';\n"
"  }\n"
"  function formatBitsPerSecond(bytesPerSecond) {\n"
"    const bits = bytesPerSecond * 8;\n"
"    if (bits >= 1e6) return (bits / 1e6).toFixed(2) + ' Mbps';\n"
"    return (bits / 1e3).toFixed(1) + ' Kbps';\n"
"  }\n"
"\n"
"  function dbfsToY(v, height) {\n"
"    const top = 0, bottom = -120; // SPECTRUM_TOP_DBFS and the floor this page assumes\n"
"    const clamped = Math.max(bottom, Math.min(top, v));\n"
"    return height * (top - clamped) / (top - bottom);\n"
"  }\n"
"\n"
"  function drawSpectrum(average, peak) {\n"
"    const w = specCanvas.width, h = specCanvas.height;\n"
"    specCtx.fillStyle = '#0a0f16';\n"
"    specCtx.fillRect(0, 0, w, h);\n"
"    plot(peak, '#e8a355');\n"
"    plot(average, '#5adcc8');\n"
"    function plot(bins, color) {\n"
"      specCtx.strokeStyle = color;\n"
"      specCtx.beginPath();\n"
"      for (let x = 0; x < w; x++) {\n"
"        const i = Math.floor(x * bins.length / w);\n"
"        const y = dbfsToY(bins[i], h);\n"
"        if (x === 0) specCtx.moveTo(x, y); else specCtx.lineTo(x, y);\n"
"      }\n"
"      specCtx.stroke();\n"
"    }\n"
"  }\n"
"\n"
"  function colorFor(dbfs) {\n"
"    const t = Math.max(0, Math.min(1, (dbfs + 100) / 90));\n"
"    const r = Math.round(20 + 220 * t), g = Math.round(30 + 140 * t), b = Math.round(50 + 60 * (1 - t));\n"
"    return 'rgb(' + r + ',' + g + ',' + b + ')';\n"
"  }\n"
"\n"
"  function drawWaterfall() {\n"
"    const w = wfCanvas.width, h = wfCanvas.height;\n"
"    wfCtx.fillStyle = '#0a0f16';\n"
"    wfCtx.fillRect(0, 0, w, h);\n"
"    for (let r = 0; r < wfHistory.length; r++) {\n"
"      const row = wfHistory[wfHistory.length - 1 - r]; // newest at the top\n"
"      for (let x = 0; x < w; x++) {\n"
"        const i = Math.floor(x * row.length / w);\n"
"        wfCtx.fillStyle = colorFor(row[i]);\n"
"        wfCtx.fillRect(x, r, 1, 1);\n"
"      }\n"
"    }\n"
"  }\n"
"\n"
"  connect();\n"
"})();\n"
"</script>\n";

#endif
